server.port=8093
spring.application.name=supply-service

# DATABASE
spring.datasource.url=jdbc:postgresql://supply-db:5432/supply_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ❌ SUPPRIMER CES LIGNES (Feign utilise Eureka)
# services.product.url=
# services.supplier.url=

# EUREKA
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# KAFKA
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=supply-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.stock.supply_service.event.StockLowEvent

# ACTUATOR
management.endpoints.web.exposure.include=*