server.port=8093
spring.application.name=supply-service

# DATABASE
spring.datasource.url=jdbc:postgresql://supply-db:5432/supply_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# EUREKA
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# KAFKA
spring.kafka.bootstrap-servers=kafka:9092